name: Pet-Clinic Test
on:
  - push
jobs:
  verify-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
          cache: 'maven'
      - name: Run Verify
        run: ./mvnw verify
